/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2023-07-01 12:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.CardHistoryDto;
import java.util.ArrayList;
import javax.servlet.http.HttpSession;
import dto.CardHistoryDto;
import java.util.ArrayList;
import javax.servlet.http.HttpSession;

public final class cardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/sidebar.jsp", Long.valueOf(1688208314516L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("dto.CardHistoryDto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>카드 사용 내역 조회</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  function handleInput() {\r\n");
      out.write("    var selectOption = document.getElementById(\"mySelect\").value;\r\n");
      out.write("    var inputField = document.getElementById(\"customPeriodInput\");\r\n");
      out.write("    var input = document.getElementById(\"inputField\");\r\n");
      out.write("    \r\n");
      out.write("    if (selectOption === \"custom\") {\r\n");
      out.write("    \tinput.value = null;\r\n");
      out.write("    \tinputField.style.display = \"block\";\r\n");
      out.write("      \r\n");
      out.write("    } else {\r\n");
      out.write("      inputField.style.display = \"none\";\r\n");
      out.write("      if(selectOption !== \"title\"){\r\n");
      out.write("    \tinput.value = selectOption;\r\n");
      out.write("      \tdocument.forms[\"periodOption\"].submit();\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function changeInputField() {\r\n");
      out.write("\t    var keywordInput = document.getElementById(\"keywordInput\");\r\n");
      out.write("\t    var selectElement = document.getElementById(\"searchForm\").elements[\"searchType\"];\r\n");
      out.write("\t    var selectedValue = selectElement.options[selectElement.selectedIndex].value;\r\n");
      out.write("\r\n");
      out.write("\t    if (selectedValue === \"customerId\") {\r\n");
      out.write("\t        keywordInput.placeholder = \"고객 ID를 입력하세요.\";\r\n");
      out.write("\t    \tdocument.getElementById(\"searchForm\").elements[\"action\"].value = \"searchId\";\r\n");
      out.write("\t    } else if (selectedValue === \"cardId\") {\r\n");
      out.write("\t    \tkeywordInput.placeholder = \"카드 ID를 입력하세요.\";\r\n");
      out.write("\t      \tdocument.getElementById(\"searchForm\").elements[\"action\"].value = \"searchCardId\";\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t    \tkeywordInput.placeholder = \"고객ID or 카드ID을 선택하세요.\";\r\n");
      out.write("\t    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("  $('#dataTable').DataTable({\r\n");
      out.write("    \"order\": [[0, \"desc\"]],\r\n");
      out.write("    \"destroy\" :true,\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css\" />\r\n");
      out.write("\r\n");
      out.write(" \t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/default.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this page -->\r\n");
      out.write("    <link href=\"resources/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>    \r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tlabel {\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"resources/css/lookup.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>사이드 바</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\" >\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - projectName -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"bi bi-credit-card\" style=\"color:white;\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\" style=\"color:white;\"> Card Tracker</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Nav Item - 조회 Menu -->\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"bi bi-table\" ></i>\r\n");
      out.write("                    <span>조회</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">- 고객 정보 조회</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" >신상 정보 조회</a>\r\n");
      out.write("                        <a class=\"collapse-item\" >보유한 카드 내역 조회</a>\r\n");
      out.write("                        <a class=\"collapse-item\" >계좌 정보 조회</a>\r\n");
      out.write("                         <h6 class=\"collapse-header\">- 카드 상품 조회</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" >카드 상품 조회</a>\r\n");
      out.write("                        <h6 class=\"collapse-header\">- 카드 사용 내역 조회</h6>\r\n");
      out.write("                        <form class=\"collapse-item\" id=\"cardForm\" method=\"GET\" action=\"CardServlet\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"hidden\" name=\"action\" value=\"list\" />\r\n");
      out.write("\t\t\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"#\" onclick=\"document.getElementById('cardForm').submit(); return false;\">카드 사용 내역</a>\r\n");
      out.write("                        <a class=\"collapse-item\" >카드 월별 명세서</a>\r\n");
      out.write("                        <a class=\"collapse-item\" >할부 내역</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - 수정 Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\r\n");
      out.write("                    <i class=\"bi bi-pencil-square\"></i>\r\n");
      out.write("                    <span>수정</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">- 정보 수정</h6>\r\n");
      out.write("                        <a class=\"collapse-item\">고객 정보 수정</a>\r\n");
      out.write("                        <a class=\"collapse-item\">카드 정보 수정</a>\r\n");
      out.write("                        <a class=\"collapse-item\" >카드 정지</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Topbar 로그아웃 버튼 -->\r\n");
      out.write("                <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("                    <div class=\"ml-auto\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"\" >\r\n");
      out.write("                    <i class=\"bi bi-box-arrow-left\" style=\"font-size: 15px; text-align:center; \"></i>\r\n");
      out.write("                    <span>로그아웃</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End of Topbar -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"resources/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <!-- Begin Page Content -->\r\n");
      out.write("       <div class=\"container-fluid\">\r\n");
      out.write("           \r\n");
      out.write("           <!-- 카드 사용 내역 datatable -->\r\n");
      out.write("             <div class=\"card shadow mb-4\">\r\n");
      out.write("                 <div class=\"card-header py-3\">\r\n");
      out.write("                     <h4 class=\"m-0 font-weight-bold text-primary\">카드 사용 내역</h4>\r\n");
      out.write("                 </div>\r\n");
      out.write("             <div class=\"card-body\">\r\n");
      out.write("\t\t\t<div id=\"inputContainer\">\r\n");
      out.write("\t\t\t<form id=\"searchForm\" method=\"GET\" action=\"CardServlet\">\r\n");
      out.write("\t\t\t  <select name=\"searchType\" onchange=\"changeInputField()\">\r\n");
      out.write("\t\t\t  \t<option value=\"title\">검색 조건</option>\r\n");
      out.write("\t\t\t    <option value=\"customerId\">고객 ID</option>\r\n");
      out.write("\t\t\t    <option value=\"cardId\">카드 ID</option>\r\n");
      out.write("\t\t\t  </select>\r\n");
      out.write("\t\t\t  <input id=\"keywordInput\" type=\"text\" name=\"keyword\" placeholder=\"고객ID or 카드ID을 선택하세요.\">\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"action\">\r\n");
      out.write("\t\t\t  <input class=\"btn btn-primary btn-sm\" type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form name=\"periodOption\" method=\"GET\" action=\"CardServlet\">\r\n");
      out.write("\t\t\t  <div class =\"selectBox\">\r\n");
      out.write("\t\t\t \t  <div id=\"customPeriodInput\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\" id=\"inputField\" name=\"keyword\" placeholder=\"기간을 입력하세요.(개월단위)\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"hidden\" name=\"action\" value=\"searchPeriod\" />\r\n");
      out.write("\t\t\t\t\t  <input class=\"btn btn-primary btn-sm\" type=\"submit\" value=\"조회하기\">\r\n");
      out.write("\t\t\t\t  </div> \r\n");
      out.write("\t\t\t\t  <select name=\"list\" id=\"mySelect\" onchange=\"handleInput()\">\r\n");
      out.write("\t\t\t\t  \t<option value=\"title\">월별 조회하기</option>\r\n");
      out.write("\t\t\t\t    <option value=\"custom\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">1개월</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">3개월</option>\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        \t<th>결제 순번</th>\r\n");
      out.write("                            <th>카드ID</th>\r\n");
      out.write("                            <th>사용자ID</th>\r\n");
      out.write("                            <th>가맹점명</th>\r\n");
      out.write("                            <th>결제금액</th>\r\n");
      out.write("                            <th>계좌잔액</th>\r\n");
      out.write("                            <th>거래일자</th>\r\n");
      out.write("                            <th>카테고리명</th>\r\n");
      out.write("                            <th>할부여부</th>\r\n");
      out.write("                            <th>할부개월</th>\r\n");
      out.write("                            <th>신용/체크</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("        \t\t\t<tbody>\r\n");
      out.write("\t\t\t        ");
 ArrayList<CardHistoryDto> list = (ArrayList<CardHistoryDto>) request.getAttribute("list");
			        for (CardHistoryDto data : list) { 
      out.write("\r\n");
      out.write("\t\t\t            <tr>\r\n");
      out.write("\t\t\t            \t<td>");
      out.print( data.getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getCardId() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getFranchisee() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getPayment() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getBalance() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getFCategory() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getIsIns() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getInsMonth() );
      out.write("</td>\r\n");
      out.write("\t\t\t                <td>");
      out.print( data.getCardType() );
      out.write("</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t        ");
 } 
      out.write("\r\n");
      out.write("                         </tbody>\r\n");
      out.write("                       </table>\r\n");
      out.write("                       </div>\r\n");
      out.write("                </div>\r\n");
      out.write("     \t\t</div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("       <div class=\"container my-auto\">\r\n");
      out.write("           <div class=\"copyright text-center my-auto\">\r\n");
      out.write("               <span>digital Hana路 &copy; card Tracker </span>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- End of Footer -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
